Repository wecode-bootcamp-korea/30-westagram-backend-3-team, pull requests merged in 2022-02, with the labels that each got.

#1 [김가람휘] Mission 1 : Django 초기 세팅
  students/westagram/.gitignore
  students/westagram/manage.py
  students/westagram/requirements.txt
  students/westagram/westagram/__init__.py
  students/westagram/westagram/asgi.py
  students/westagram/westagram/settings.py
  students/westagram/westagram/urls.py
  students/westagram/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#3 [김광일] Mission1 : Django 초기 세팅
  students/gwangil/.gitignore
  students/gwangil/manage.py
  students/gwangil/requirements.txt
  students/gwangil/westagram/__init__.py
  students/gwangil/westagram/asgi.py
  students/gwangil/westagram/settings.py
  students/gwangil/westagram/urls.py
  students/gwangil/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#4 [박영서] Mission1 : Django 초기 세팅
  students/yeongseo/westagram/.gitignore
  students/yeongseo/westagram/manage.py
  students/yeongseo/westagram/requirements.txt
  students/yeongseo/westagram/westagram/__init__.py
  students/yeongseo/westagram/westagram/asgi.py
  students/yeongseo/westagram/westagram/settings.py
  students/yeongseo/westagram/westagram/urls.py
  students/yeongseo/westagram/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#9 project initial setting
  students/jiseong/.gitignore
  students/jiseong/manage.py
  students/jiseong/requirements.txt
  students/jiseong/westagram/__init__.py
  students/jiseong/westagram/asgi.py
  students/jiseong/westagram/settings.py
  students/jiseong/westagram/urls.py
  students/jiseong/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#8 [박영서] Mission 2: 모델링
  students/yeongseo/westagram/users/__init__.py
  students/yeongseo/westagram/users/admin.py
  students/yeongseo/westagram/users/apps.py
  students/yeongseo/westagram/users/migrations/__init__.py
  students/yeongseo/westagram/users/models.py
  students/yeongseo/westagram/users/tests.py
  students/yeongseo/westagram/users/views.py
Labels: 완료

#7 [김광일] Mission 2: 모델링
  students/gwangil/users/__init__.py
  students/gwangil/users/admin.py
  students/gwangil/users/apps.py
  students/gwangil/users/migrations/0001_initial.py
  students/gwangil/users/migrations/0002_delete_user.py
  students/gwangil/users/migrations/0003_initial.py
  students/gwangil/users/migrations/0004_username_delete_user.py
  students/gwangil/users/migrations/0005_rename_username_user_alter_user_table.py
  students/gwangil/users/migrations/__init__.py
  students/gwangil/users/models.py
  students/gwangil/users/tests.py
  students/gwangil/users/views.py
  students/gwangil/westagram/settings.py
Labels: 멘토 리뷰 요청

#6 [김가람휘] Mission 2: 모델링
  students/westagram/users/__init__.py
  students/westagram/users/admin.py
  students/westagram/users/apps.py
  students/westagram/users/migrations/0001_initial.py
  students/westagram/users/migrations/0002_rename_name_user_username_remove_user_phone_number_and_more.py
  students/westagram/users/migrations/__init__.py
  students/westagram/users/models.py
  students/westagram/users/tests.py
  students/westagram/users/views.py
  students/westagram/westagram/settings.py
Labels: 멘토 리뷰 요청

#10 [김지성] Mission 2: 모델링
  students/jiseong/users/__init__.py
  students/jiseong/users/admin.py
  students/jiseong/users/apps.py
  students/jiseong/users/migrations/__init__.py
  students/jiseong/users/models.py
  students/jiseong/users/tests.py
  students/jiseong/users/views.py
Labels: 멘토 리뷰 요청

#11 [김가람휘] Mission 3: 회원가입 기능 구현
  students/westagram/users/migrations/0001_initial.py
  students/westagram/users/migrations/0002_alter_user_contact_alter_user_email_and_more.py
  students/westagram/users/migrations/0002_rename_name_user_username_remove_user_phone_number_and_more.py
  students/westagram/users/migrations/0003_alter_user_email.py
  students/westagram/users/models.py
  students/westagram/users/urls.py
  students/westagram/users/validation.py
  students/westagram/users/views.py
  students/westagram/westagram/settings.py
  students/westagram/westagram/urls.py
Labels: 완료

#12 [김광일] Mission 3: 회원가입 기능 구현
  students/gwangil/users/urls.py
  students/gwangil/users/validation.py
  students/gwangil/users/views.py
  students/gwangil/westagram/settings.py
  students/gwangil/westagram/urls.py
Labels: 멘토 리뷰 요청

#14 [김지성] Mission 3: 회원가입 기능 구현
  students/jiseong/users/migrations/0001_initial.py
  students/jiseong/users/urls.py
  students/jiseong/users/vaildators.py
  students/jiseong/users/views.py
  students/jiseong/westagram/settings.py
  students/jiseong/westagram/urls.py
Labels: 멘토 리뷰 요청

#16 [김가람휘] Mission 4: 로그인 기능 구현
  students/westagram/users/urls.py
  students/westagram/users/views.py
Labels: 멘토 리뷰 요청

#20 [김지성] Mission 4: 로그인 기능 구현
  students/jiseong/users/urls.py
  students/jiseong/users/views.py
Labels: 멘토 리뷰 요청

#19 [박영서] Mission 3: 회원가입 기능 구현
  students/yeongseo/westagram/users/migrations/0001_initial.py
  students/yeongseo/westagram/users/migrations/0002_alter_users_email.py
  students/yeongseo/westagram/users/models.py
  students/yeongseo/westagram/users/urls.py
  students/yeongseo/westagram/users/validation.py
  students/yeongseo/westagram/users/views.py
  students/yeongseo/westagram/westagram/settings.py
  students/yeongseo/westagram/westagram/urls.py
Labels: 수정 요청

#18 [김광일] Mission4 : 로그인 기능 구현
  students/gwangil/users/urls.py
  students/gwangil/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#21 [박영서] Mission4 : 로그인 기능 구현
  students/yeongseo/westagram/users/urls.py
  students/yeongseo/westagram/users/views.py
Labels: 완료

#17 [김가람휘] Mission 5: 회원가입 비밀번호 암호화 적용
  students/westagram/users/migrations/0004_alter_user_contact.py
  students/westagram/users/migrations/0005_alter_user_contact.py
  students/westagram/users/models.py
  students/westagram/users/views.py
Labels: 멘토 리뷰 요청

#22 [김지성] Mission 5: 회원가입 비밀번호 암호화 적용
  students/jiseong/users/views.py
Labels: 수정 요청

#25 [박영서] Mission 5: models.py 수정
  students/yeongseo/westagram/users/migrations/0003_user_delete_users.py
  students/yeongseo/westagram/users/models.py
Labels: 완료

#23 [박영서] Mission 5: 회원가입 비밀번호 암호화 적용
  students/yeongseo/westagram/users/views.py
Labels: 수정 요청

#27 [박영서] Mission 5: 회원가입 비밀번호 암호화 적용
  students/yeongseo/westagram/users/views.py
Labels: 멘토 리뷰 요청

#24 [김가람휘] Mission 6: 로그인 JWT 발급
  students/westagram/users/views.py
Labels: 완료

#28 [김광일] Mission 5: 회원가입 비밀번호 암호화 적용
  students/gwangil/users/views.py
Labels: 멘토 리뷰 요청

#30 [김지성] Mission 5: add get
  students/jiseong/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#31 [김지성] Mission 6: 로그인 JWT 발급
  students/jiseong/users/views.py
Labels: 멘토 리뷰 요청

#33 [김광일] Mission 6: 로그인 JWT 발급
  students/gwangil/users/migrations/0006_alter_user_phone_number.py
  students/gwangil/users/models.py
  students/gwangil/users/views.py
Labels: 멘토 리뷰 요청
